server:
  port: 8050

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/nep?characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&allowMultiQueries=true
    username: nanhu
    password: 'neu030713'
  jackson:
    time-zone: Asia/Shanghai
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      write-dates-as-timestamps: false
  web:
    resources:
      static-locations: classpath:static/,file:static/

#  security:
#    user:
#      name: user
#      password: pwd123

mybatis-plus:
  type-aliases-package: com.neusoft.neu24..entity
  configuration:
    call-setters-on-nulls: false
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/**/**Mapper.xml
  global-config:
    banner: true
    db-config:
      id-type: assign_uuid # auto assign UUID
      logic-delete-value: 0
      logic-not-delete-value: 1

logging:
  level:
    root: info
