server:
  port: 8085 # nep-common port

spring:
  application:
    name: user-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://8.130.74.245:3306/nep?characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&allowMultiQueries=true
    username: root
    password: '123456'
  jackson:
    time-zone: Asia/Shanghai
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      write-dates-as-timestamps: false

#  security:
#    user:
#      name: user
#      password: 123456

mybatis-plus:
  mapper-locations: classpath:mapper/**Mapper.xml # mapper file location
  type-aliases-package: com.neusoft.neu24.user.entity # entity class location
  configuration:
    call-setters-on-nulls: false # set null value to entity
    map-underscore-to-camel-case: true # underline to camel
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # log
  global-config:
    banner: true
    db-config:
      id-type: assign_uuid # auto assign UUID
      logic-delete-value: 0
      logic-not-delete-value: 1

# configure log output
logging:
  level:
    root: info
    com.neusoft.neu24.nepcommon.mapper: debug # print the executed SQL from Mybatis


